<?php

namespace Database\Seeders;

use App\Enums\CarClass;
use App\Enums\PartSlot;
use App\Models\CarModel;
use Illuminate\Database\Seeder;

class CarModelSeeder extends Seeder
{
    private const DURABILITY = 999;

    public function run(): void
    {
        $upgradeSlots = PartSlot::values();

        $models = [
            // ── D-class ──────────────────────────────────────────────────────
            [
                'name' => 'Veloce Astraea',
                'class' => CarClass::D,
                'rarity' => 'common',
                'image_path' => 'cars/veloce-astraea.png',
                'power' => 38,
                'acceleration' => 42,
                'weight' => 52,
                'grip' => 40,
                'handling' => 42,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 0,
                'starter' => true,
                'unlock_level' => 1,
                'active' => true,
            ],
            [
                'name' => 'Kurama Echo',
                'class' => CarClass::D,
                'rarity' => 'common',
                'image_path' => 'cars/kurama-echo.png',
                'power' => 40,
                'acceleration' => 42,
                'weight' => 50,
                'grip' => 42,
                'handling' => 43,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 3500,
                'starter' => false,
                'unlock_level' => 2,
                'active' => true,
            ],
            [
                'name' => 'Einheit Club',
                'class' => CarClass::D,
                'rarity' => 'common',
                'image_path' => 'cars/einheit-club.png',
                'power' => 44,
                'acceleration' => 44,
                'weight' => 51,
                'grip' => 44,
                'handling' => 44,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 4000,
                'starter' => false,
                'unlock_level' => 4,
                'active' => true,
            ],
            [
                'name' => 'Lumiere 26-R',
                'class' => CarClass::D,
                'rarity' => 'common',
                'image_path' => 'cars/lumiere-26-r.png',
                'power' => 43,
                'acceleration' => 47,
                'weight' => 45,
                'grip' => 43,
                'handling' => 47,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 5500,
                'starter' => false,
                'unlock_level' => 4,
                'active' => true,
            ],

            // ── C-class ──────────────────────────────────────────────────────
            [
                'name' => 'Haruka Urban',
                'class' => CarClass::C,
                'rarity' => 'uncommon',
                'image_path' => 'cars/haruka-urban.png',
                'power' => 48,
                'acceleration' => 50,
                'weight' => 44,
                'grip' => 46,
                'handling' => 49,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 11000,
                'starter' => false,
                'unlock_level' => 5,
                'active' => true,
            ],
            [
                'name' => 'Veloce Astraea SV',
                'class' => CarClass::C,
                'rarity' => 'uncommon',
                'image_path' => 'cars/veloce-astraea-sv.png',
                'power' => 53,
                'acceleration' => 54,
                'weight' => 47,
                'grip' => 51,
                'handling' => 52,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 9000,
                'starter' => false,
                'unlock_level' => 7,
                'active' => true,
            ],
            [
                'name' => 'Kaiser Beringer',
                'class' => CarClass::C,
                'rarity' => 'uncommon',
                'image_path' => 'cars/kaiser-beringer.png',
                'power' => 55,
                'acceleration' => 51,
                'weight' => 55,
                'grip' => 53,
                'handling' => 51,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 18000,
                'starter' => false,
                'unlock_level' => 8,
                'active' => true,
            ],
            [
                'name' => 'Veloce Astraea SVR',
                'class' => CarClass::C,
                'rarity' => 'uncommon',
                'image_path' => 'cars/veloce-astraea-corsa.png',
                'power' => 58,
                'acceleration' => 56,
                'weight' => 48,
                'grip' => 54,
                'handling' => 53,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 14000,
                'starter' => false,
                'unlock_level' => 9,
                'active' => true,
            ],

            // ── B-class ──────────────────────────────────────────────────────
            [
                'name' => 'Kaze Stormbringer Tourer',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/kaze-stormbringer-tourer.png',
                'power' => 51,
                'acceleration' => 50,
                'weight' => 53,
                'grip' => 50,
                'handling' => 50,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 48000,
                'starter' => false,
                'unlock_level' => 5,
                'active' => true,
            ],
            [
                'name' => 'Bayerische M34',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/bayerische-m34.png',
                'power' => 62,
                'acceleration' => 59,
                'weight' => 52,
                'grip' => 57,
                'handling' => 58,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 28000,
                'starter' => false,
                'unlock_level' => 10,
                'active' => true,
            ],
            [
                'name' => 'Kaze Stormbringer',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/kaze-stormbringer.png',
                'power' => 70,
                'acceleration' => 67,
                'weight' => 50,
                'grip' => 65,
                'handling' => 64,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 42000,
                'starter' => false,
                'unlock_level' => 13,
                'active' => true,
            ],

            // ── A-class ──────────────────────────────────────────────────────
            [
                'name' => 'Amaterasu Rotor-7',
                'class' => CarClass::A,
                'rarity' => 'rare',
                'image_path' => 'cars/amaterasu-rotor-7.png',
                'power' => 72,
                'acceleration' => 70,
                'weight' => 44,
                'grip' => 63,
                'handling' => 70,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 85000,
                'starter' => false,
                'unlock_level' => 13,
                'active' => true,
            ],
            [
                'name' => 'Zenith S-Sovereign',
                'class' => CarClass::A,
                'rarity' => 'rare',
                'image_path' => 'cars/zenith-s-sovereign.png',
                'power' => 75,
                'acceleration' => 73,
                'weight' => 46,
                'grip' => 68,
                'handling' => 72,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 65000,
                'starter' => false,
                'unlock_level' => 15,
                'active' => true,
            ],

            // ── S-class ──────────────────────────────────────────────────────
            [
                'name' => 'Shogun Apex VIII',
                'class' => CarClass::S,
                'rarity' => 'rare',
                'image_path' => 'cars/shogun-apex-viii.png',
                'power' => 78,
                'acceleration' => 75,
                'weight' => 48,
                'grip' => 73,
                'handling' => 72,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 120000,
                'starter' => false,
                'unlock_level' => 16,
                'active' => true,
            ],

            // ── B-class continuations (levels 17–28) ─────────────────────────
            [
                'name' => 'Celeste Vento GT',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/celeste-vento-gt.png',
                'power' => 62,
                'acceleration' => 60,
                'weight' => 50,
                'grip' => 58,
                'handling' => 60,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 55000,
                'starter' => false,
                'unlock_level' => 17,
                'active' => true,
            ],
            [
                'name' => 'Raijin Type-R',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/raijin-type-r.png',
                'power' => 64,
                'acceleration' => 62,
                'weight' => 50,
                'grip' => 60,
                'handling' => 59,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 68000,
                'starter' => false,
                'unlock_level' => 19,
                'active' => true,
            ],
            [
                'name' => 'Nordvik GT220',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/nordvik-gt220.png',
                'power' => 63,
                'acceleration' => 59,
                'weight' => 52,
                'grip' => 59,
                'handling' => 61,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 80000,
                'starter' => false,
                'unlock_level' => 21,
                'active' => true,
            ],
            [
                'name' => 'Kurama RS-400',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/kurama-rs-400.png',
                'power' => 65,
                'acceleration' => 62,
                'weight' => 51,
                'grip' => 61,
                'handling' => 62,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 92000,
                'starter' => false,
                'unlock_level' => 23,
                'active' => true,
            ],
            [
                'name' => 'Einheit Turbo S',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/einheit-turbo-s.png',
                'power' => 66,
                'acceleration' => 63,
                'weight' => 51,
                'grip' => 62,
                'handling' => 61,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 105000,
                'starter' => false,
                'unlock_level' => 25,
                'active' => true,
            ],
            [
                'name' => 'Tokai S-Spec',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/tokai-s-spec.png',
                'power' => 67,
                'acceleration' => 64,
                'weight' => 50,
                'grip' => 62,
                'handling' => 63,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 120000,
                'starter' => false,
                'unlock_level' => 27,
                'active' => true,
            ],

            // ── A-class continuations (levels 29–50) ─────────────────────────
            [
                'name' => 'Veloce Corsa R',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/veloce-corsa-r.png',
                'power' => 67,
                'acceleration' => 66,
                'weight' => 48,
                'grip' => 64,
                'handling' => 66,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 140000,
                'starter' => false,
                'unlock_level' => 29,
                'active' => true,
            ],
            [
                'name' => 'Haruka GT-S',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/haruka-gt-s.png',
                'power' => 68,
                'acceleration' => 67,
                'weight' => 46,
                'grip' => 64,
                'handling' => 66,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 160000,
                'starter' => false,
                'unlock_level' => 31,
                'active' => true,
            ],
            [
                'name' => 'Raijin Storm V',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/raijin-storm-v.png',
                'power' => 70,
                'acceleration' => 68,
                'weight' => 48,
                'grip' => 65,
                'handling' => 67,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 185000,
                'starter' => false,
                'unlock_level' => 33,
                'active' => true,
            ],
            [
                'name' => 'Amaterasu Apex',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/amaterasu-apex.png',
                'power' => 70,
                'acceleration' => 68,
                'weight' => 46,
                'grip' => 66,
                'handling' => 68,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 210000,
                'starter' => false,
                'unlock_level' => 35,
                'active' => true,
            ],
            [
                'name' => 'Kaiser M-Sport',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/kaiser-m-sport.png',
                'power' => 71,
                'acceleration' => 68,
                'weight' => 52,
                'grip' => 66,
                'handling' => 67,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 240000,
                'starter' => false,
                'unlock_level' => 37,
                'active' => true,
            ],
            [
                'name' => 'Celeste Astra GT',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/celeste-astra-gt.png',
                'power' => 71,
                'acceleration' => 69,
                'weight' => 47,
                'grip' => 67,
                'handling' => 68,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 270000,
                'starter' => false,
                'unlock_level' => 39,
                'active' => true,
            ],
            [
                'name' => 'Fenrir V8 GT',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/fenrir-v8-gt.png',
                'power' => 72,
                'acceleration' => 68,
                'weight' => 53,
                'grip' => 66,
                'handling' => 67,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 300000,
                'starter' => false,
                'unlock_level' => 41,
                'active' => true,
            ],
            [
                'name' => 'Tokai Omega',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/tokai-omega.png',
                'power' => 72,
                'acceleration' => 70,
                'weight' => 48,
                'grip' => 67,
                'handling' => 68,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 340000,
                'starter' => false,
                'unlock_level' => 43,
                'active' => true,
            ],
            [
                'name' => 'Shogun Kai',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/shogun-kai.png',
                'power' => 73,
                'acceleration' => 70,
                'weight' => 48,
                'grip' => 68,
                'handling' => 69,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 380000,
                'starter' => false,
                'unlock_level' => 46,
                'active' => true,
            ],
            [
                'name' => 'Nordvik RS500',
                'class' => CarClass::A,
                'rarity' => 'epic',
                'image_path' => 'cars/nordvik-rs500.png',
                'power' => 73,
                'acceleration' => 71,
                'weight' => 50,
                'grip' => 69,
                'handling' => 70,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 420000,
                'starter' => false,
                'unlock_level' => 49,
                'active' => true,
            ],

            // ── S-class continuations (levels 52–100) ────────────────────────
            [
                'name' => 'Raijin S-Zero',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => 'cars/raijin-s-zero.png',
                'power' => 74,
                'acceleration' => 72,
                'weight' => 48,
                'grip' => 70,
                'handling' => 70,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 480000,
                'starter' => false,
                'unlock_level' => 52,
                'active' => true,
            ],
            [
                'name' => 'Zenith X-Ultra',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => 'cars/zenith-x-ultra.png',
                'power' => 74,
                'acceleration' => 72,
                'weight' => 46,
                'grip' => 70,
                'handling' => 71,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 540000,
                'starter' => false,
                'unlock_level' => 55,
                'active' => true,
            ],
            [
                'name' => 'Amaterasu GT-R7',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => 'cars/amaterasu-gt-r7.png',
                'power' => 75,
                'acceleration' => 73,
                'weight' => 46,
                'grip' => 71,
                'handling' => 72,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 600000,
                'starter' => false,
                'unlock_level' => 58,
                'active' => true,
            ],
            [
                'name' => 'Celeste Veloce SV',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => 'cars/celeste-veloce-sv.png',
                'power' => 75,
                'acceleration' => 73,
                'weight' => 47,
                'grip' => 71,
                'handling' => 72,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 660000,
                'starter' => false,
                'unlock_level' => 61,
                'active' => true,
            ],
            [
                'name' => 'Tokai Phantom',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => 'cars/tokai-phantom.png',
                'power' => 75,
                'acceleration' => 74,
                'weight' => 48,
                'grip' => 72,
                'handling' => 73,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 730000,
                'starter' => false,
                'unlock_level' => 64,
                'active' => true,
            ],
            [
                'name' => 'Kaze Tempest',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => 'cars/kaze-tempest.png',
                'power' => 76,
                'acceleration' => 74,
                'weight' => 49,
                'grip' => 72,
                'handling' => 73,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 800000,
                'starter' => false,
                'unlock_level' => 67,
                'active' => true,
            ],
            [
                'name' => 'Bayerische M60',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => 'cars/bayerische-m60.png',
                'power' => 76,
                'acceleration' => 74,
                'weight' => 50,
                'grip' => 73,
                'handling' => 73,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 880000,
                'starter' => false,
                'unlock_level' => 70,
                'active' => true,
            ],
            [
                'name' => 'Fenrir R-900',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => 'cars/fenrir-r-900.png',
                'power' => 76,
                'acceleration' => 75,
                'weight' => 50,
                'grip' => 73,
                'handling' => 74,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 960000,
                'starter' => false,
                'unlock_level' => 73,
                'active' => true,
            ],
            [
                'name' => 'Shogun Apex X',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => 'cars/shogun-apex-x.png',
                'power' => 77,
                'acceleration' => 75,
                'weight' => 48,
                'grip' => 73,
                'handling' => 74,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 1050000,
                'starter' => false,
                'unlock_level' => 76,
                'active' => true,
            ],
            [
                'name' => 'Kaiser Ultima',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => null,
                'power' => 77,
                'acceleration' => 76,
                'weight' => 52,
                'grip' => 74,
                'handling' => 75,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 1150000,
                'starter' => false,
                'unlock_level' => 79,
                'active' => true,
            ],
            [
                'name' => 'Raijin Absolute',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => null,
                'power' => 77,
                'acceleration' => 76,
                'weight' => 48,
                'grip' => 74,
                'handling' => 75,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 1250000,
                'starter' => false,
                'unlock_level' => 82,
                'active' => true,
            ],
            [
                'name' => 'Zenith S-Maxima',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => null,
                'power' => 78,
                'acceleration' => 77,
                'weight' => 47,
                'grip' => 75,
                'handling' => 75,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 1350000,
                'starter' => false,
                'unlock_level' => 85,
                'active' => true,
            ],
            [
                'name' => 'Celeste Infinita',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => null,
                'power' => 78,
                'acceleration' => 77,
                'weight' => 48,
                'grip' => 75,
                'handling' => 76,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 1460000,
                'starter' => false,
                'unlock_level' => 88,
                'active' => true,
            ],
            [
                'name' => 'Tokai Ghost',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => null,
                'power' => 79,
                'acceleration' => 78,
                'weight' => 48,
                'grip' => 76,
                'handling' => 76,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 1580000,
                'starter' => false,
                'unlock_level' => 91,
                'active' => true,
            ],
            [
                'name' => 'Amaterasu Final Form',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => null,
                'power' => 79,
                'acceleration' => 78,
                'weight' => 47,
                'grip' => 77,
                'handling' => 77,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 1700000,
                'starter' => false,
                'unlock_level' => 94,
                'active' => true,
            ],
            [
                'name' => 'Kaze Godspeed',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => null,
                'power' => 79,
                'acceleration' => 79,
                'weight' => 49,
                'grip' => 77,
                'handling' => 77,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 1850000,
                'starter' => false,
                'unlock_level' => 97,
                'active' => true,
            ],
            [
                'name' => 'Shogun Apex Zero',
                'class' => CarClass::S,
                'rarity' => 'legendary',
                'image_path' => null,
                'power' => 80,
                'acceleration' => 80,
                'weight' => 48,
                'grip' => 78,
                'handling' => 78,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 2000000,
                'starter' => false,
                'unlock_level' => 100,
                'active' => true,
            ],
        ];

        foreach ($models as $model) {
            $model['block_level'] = $model['unlock_level'] + 5;

            CarModel::query()->updateOrCreate(
                ['name' => $model['name']],
                $model,
            );
        }

        $catalogNames = array_column($models, 'name');

        CarModel::query()
            ->whereNotIn('name', $catalogNames)
            ->update([
                'active' => false,
                'starter' => false,
            ]);
    }
}
