<?php

namespace Database\Seeders;

use App\Enums\CarClass;
use App\Enums\PartSlot;
use App\Models\CarModel;
use Illuminate\Database\Seeder;

class CarModelSeeder extends Seeder
{
    private const DURABILITY = 999;

    public function run(): void
    {
        $upgradeSlots = PartSlot::values();

        $models = [
            // Paczka 1 — podstawowe i usportowione hatchbacki
            [
                'name' => 'Veloce Astraea',
                'class' => CarClass::D,
                'rarity' => 'common',
                'image_path' => 'cars/veloce-astraea.png',
                'power' => 44,
                'acceleration' => 49,
                'weight' => 52,
                'grip' => 46,
                'handling' => 48,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 0,
                'starter' => true,
                'unlock_level' => 1,
                'active' => true,
            ],
            [
                'name' => 'Kurama Echo',
                'class' => CarClass::D,
                'rarity' => 'common',
                'image_path' => 'cars/kurama-echo.png',
                'power' => 47,
                'acceleration' => 49,
                'weight' => 50,
                'grip' => 49,
                'handling' => 50,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 3500,
                'starter' => false,
                'unlock_level' => 2,
                'active' => true,
            ],
            [
                'name' => 'Einheit Club',
                'class' => CarClass::D,
                'rarity' => 'common',
                'image_path' => 'cars/einheit-club.png',
                'power' => 52,
                'acceleration' => 51,
                'weight' => 51,
                'grip' => 52,
                'handling' => 51,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 4000,
                'starter' => false,
                'unlock_level' => 4,
                'active' => true,
            ],
            [
                'name' => 'Veloce Astraea SV',
                'class' => CarClass::C,
                'rarity' => 'uncommon',
                'image_path' => 'cars/veloce-astraea-sv.png',
                'power' => 62,
                'acceleration' => 63,
                'weight' => 47,
                'grip' => 60,
                'handling' => 61,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 9000,
                'starter' => false,
                'unlock_level' => 7,
                'active' => true,
            ],
            [
                'name' => 'Veloce Astraea SVR',
                'class' => CarClass::C,
                'rarity' => 'uncommon',
                'image_path' => 'cars/veloce-astraea-corsa.png',
                'power' => 68,
                'acceleration' => 66,
                'weight' => 48,
                'grip' => 63,
                'handling' => 62,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 14000,
                'starter' => false,
                'unlock_level' => 9,
                'active' => true,
            ],
            [
                'name' => 'Lumiere 26-R',
                'class' => CarClass::D,
                'rarity' => 'common',
                'image_path' => 'cars/lumiere-26-r.png',
                'power' => 50,
                'acceleration' => 55,
                'weight' => 45,
                'grip' => 51,
                'handling' => 55,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 5500,
                'starter' => false,
                'unlock_level' => 4,
                'active' => true,
            ],
            [
                'name' => 'Haruka Urban',
                'class' => CarClass::C,
                'rarity' => 'uncommon',
                'image_path' => 'cars/haruka-urban.png',
                'power' => 56,
                'acceleration' => 58,
                'weight' => 44,
                'grip' => 54,
                'handling' => 57,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 11000,
                'starter' => false,
                'unlock_level' => 5,
                'active' => true,
            ],
            [
                'name' => 'Kaiser Beringer',
                'class' => CarClass::C,
                'rarity' => 'uncommon',
                'image_path' => 'cars/kaiser-beringer.png',
                'power' => 64,
                'acceleration' => 60,
                'weight' => 55,
                'grip' => 62,
                'handling' => 60,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 18000,
                'starter' => false,
                'unlock_level' => 8,
                'active' => true,
            ],
            [
                'name' => 'Bayerische M34',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/bayerische-m34.png',
                'power' => 72,
                'acceleration' => 69,
                'weight' => 52,
                'grip' => 67,
                'handling' => 68,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 28000,
                'starter' => false,
                'unlock_level' => 10,
                'active' => true,
            ],
            [
                'name' => 'Kaze Stormbringer',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/kaze-stormbringer.png',
                'power' => 82,
                'acceleration' => 78,
                'weight' => 50,
                'grip' => 76,
                'handling' => 75,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 42000,
                'starter' => false,
                'unlock_level' => 13,
                'active' => true,
            ],
            [
                'name' => 'Kaze Stormbringer Tourer',
                'class' => CarClass::B,
                'rarity' => 'rare',
                'image_path' => 'cars/kaze-stormbringer-tourer.png',
                'power' => 60,
                'acceleration' => 58,
                'weight' => 53,
                'grip' => 59,
                'handling' => 58,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 48000,
                'starter' => false,
                'unlock_level' => 5,
                'active' => true,
            ],
            [
                'name' => 'Zenith S-Sovereign',
                'class' => CarClass::A,
                'rarity' => 'rare',
                'image_path' => 'cars/zenith-s-sovereign.png',
                'power' => 88,
                'acceleration' => 86,
                'weight' => 46,
                'grip' => 80,
                'handling' => 84,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 65000,
                'starter' => false,
                'unlock_level' => 15,
                'active' => true,
            ],
            [
                'name' => 'Amaterasu Rotor-7',
                'class' => CarClass::A,
                'rarity' => 'rare',
                'image_path' => 'cars/amaterasu-rotor-7.png',
                'power' => 84,
                'acceleration' => 82,
                'weight' => 44,
                'grip' => 74,
                'handling' => 82,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 85000,
                'starter' => false,
                'unlock_level' => 13,
                'active' => true,
            ],
            [
                'name' => 'Shogun Apex VIII',
                'class' => CarClass::S,
                'rarity' => 'rare',
                'image_path' => 'cars/shogun-apex-viii.png',
                'power' => 92,
                'acceleration' => 88,
                'weight' => 48,
                'grip' => 86,
                'handling' => 84,
                'durability' => self::DURABILITY,
                'upgrade_slots' => $upgradeSlots,
                'price' => 120000,
                'starter' => false,
                'unlock_level' => 16,
                'active' => true,
            ],
        ];

        foreach ($models as $model) {
            $model['block_level'] = $model['unlock_level'] + 5;

            CarModel::query()->updateOrCreate(
                ['name' => $model['name']],
                $model,
            );
        }

        $catalogNames = array_column($models, 'name');

        CarModel::query()
            ->whereNotIn('name', $catalogNames)
            ->update([
                'active' => false,
                'starter' => false,
            ]);
    }
}
